SmartBear/swaggerhub-cli

- README.md
This reverts commit 6f6e5f75e08b61648986cdf0ebcbe51230eb9d15.
> Remove an extra line from README

- README.md
- package.json
Edit description and setup in README
- Also adds Domain commands to README
- Changed font size of commands (Can revert this)
> docs(Update README): Add description and edit setup

- README.md
- package.json
> fix(Update Version): Bump to 0.2.8

- src/commands/api/create.js
- src/commands/api/get.js
- src/commands/api/publish.js
- src/commands/api/setdefault.js
- src/commands/api/unpublish.js
- src/commands/api/update.js
- src/support/command/base-command.js
- src/support/command/handle-response.js
- src/support/command/parse-input.js
- test/support/parse-input.test.js
- Deduce `isVersionRequired` from args
- Simplify identifier validation logic
-
> STEAM-3733 Simplify getIdentifier

- src/commands/api/get.js
- src/utils/general.js
- test/commands/api/get.test.js
- test/utils/general.test.js
Fixes # or adds feature x
-
-
-
> Pretty print json api

- README.md
- package-lock.json
- package.json
- src/config/index.js
- test/support/config.test.js
Adds oclif/plugins plugin
- Adds `@oclif/plugins` which supports installing 3rd party plugins
- Add documentation and point to an example plugin
> Add oclif plugin support

- .github/CODEOWNERS
- README.md
- package-lock.json
- package.json
- Clean CODEOWNERS file
- Update version to 0.2.9
> docs(Update README): Add plugins commands to readme.md

- README.md
- src/commands/api/validate.js
- Add examples to api:validate command
- Enable -h flag for api:validate command
> fix: Update validate to include examples and fix -h help

- README.md
- package.json
> Update for release 0.2.10

- README.md
- src/commands/api/update.js
- src/template-strings/info.js
- test/commands/api/update.test.js
Adds feature publish and setdefault flags to update command
> api:update:  publish and setdefault flags added with tests

- README.md
- package.json
> Update for 0.2.11 release

- README.md
- package-lock.json
- package.json
- Updating the CLI to version 0.2.12
- Updated README.md with the added features
> Creating CLI 0.2.12 release

- examples/integrations/README.md
- examples/integrations/bitbucket_cloud.json
- examples/integrations/bitbucket_server.json
- examples/integrations/github_advanced.json
- examples/integrations/github_basic.json
- examples/integrations/gitlab_integration.json
* Update readme to list the properties for creating a Bitbucket Cloud and Bitbucket Server integrations
* Add Bitbucket Cloud and Bitbucket server examples
> Add Bitbucket Cloud/Server documentation and examples

- examples/integrations/README.md
`ignoredPath` -> `ignoredPaths`
> Fix a typo in integration config docs

- README.md
- package.json
> Update README for release of 0.2.13

- README.md
- package-lock.json
- package.json
Updating Swagger CLI version to v0.2.14
> Prepare v0.2.14 release

- src/commands/api/create.js
- src/commands/api/get.js
- src/commands/api/update.js
- src/commands/domain/get.js
- src/support/command/base-command.js
- src/support/command/handle-response.js
- src/utils/general.js
- test/commands/api/get.test.js
- test/commands/api/update.test.js
- test/commands/api/validate.test.js
- test/commands/domain/get.test.js
- test/hooks/setup-config.test.js
- test/support/handle-response.test.js
- test/support/http.test.js
- test/utils/general.test.js
- Mainly adding small tests to increase code coverage
- Some changes in source code to log better messages
> test: Add tests to get 100% code coverage

- examples/integrations/README.md
- examples/integrations/amazon_api_gateway.json
> docs: Update integration properties to table format

- README.md
- package-lock.json
- package.json
> chore(Release 0.2.15): Update versions

- README.md
- src/commands/integration/get.js
- src/config/index.js
- src/requests/api.js
- src/support/command/parse-input.js
- test/commands/integration/get.test.js
- test/support/config.test.js
Adds `integration:get` command
> feat(Integrations): Add get integration command

- examples/integrations/README.md
> docs: Update On-Premise note in integration README

- README.md
- package-lock.json
- package.json
> chore: Update version before release of 0.3.0

- src/commands/project/delete.js
- src/commands/project/member/list.js
- src/commands/project/spec/add.js
- src/commands/project/update.js
- src/requests/project.js
- src/support/command/parse-input.js
- src/template-strings/info.js
- test/commands/project/delete.test.js
- test/commands/project/member/list.test.js
- test/commands/project/spec/add.test.js
- test/commands/project/update.test.js
Added functionality to delete a project
Part of #199 
- Added command `swaggerhub project:delete OWNER/PROJECT_NAME`
> feat: Added functionality to delete a project

- README.md
- package.json
- src/commands/project/member/list.js
Bumped package version to v0.6.0 in package.json and updated README.md
> chore: Bumped package version to v0.6.0 in package.json and updated README.md

- README.md
- package-lock.json
- package.json
> chore: Update version for release 0.6.1

- README.md
- package-lock.json
- package.json
Bump versions and update README for v0.6.3 release
> chore: bump versions for release

- README.md
- package-lock.json
- package.json
Bump versions and update README for release
> Bump versions for release

- src/commands/api/validate.js
- test/commands/api/validate.test.js
Updates endpoint consumed by api:validate command after standardization refactor.
> Updated endpoint in api:validate command

- .github/workflows/release-on-github.yaml
- package-lock.json
This PR:
- Fixes the README generating part of the release job
- Regenerates the package-lock.json file to use v3
> Fix release job and regenerate lock file

- .github/dependabot.yaml
- .github/release.yaml
Change dependabot cadence to weekly and add section to release notes template for dependencies
> Change dependabot cadence to weekly

- src/config/index.js
This pull request includes an update to the URL validation logic in the `src/config/index.js` file to improve readability and correctness.
Improvements to URL validation:
* [`src/config/index.js`](diffhunk://#diff-1523e3000d64e09cd6eb8370a4568715090b6763fd9192f61ab6044ac6d86fa9R24-R27): Modified the `isURLValid` function to use the `URL` constructor for parsing the `SWAGGERHUB_URL`, and updated the validation conditions to check the `hostname` and `pathname` properties of the `URL` object.
This change will close one security code scanning advisory.
> fix: more strict regex/host name checks

- .github/workflows/deploy-release.yaml
- .github/workflows/release-on-github.yaml
This PR is a testing of the CI flow. To ble closed after pipelines are properly fired.
Shall not introduce any changes to the repo nor to t
> the release job updates versions, creates readme and release PR

- .github/workflows/release-on-github.yaml
This PR fixes the release process with proper call of git cli
> fix: git push was missing the branch

- README.md
- package-lock.json
- package.json
This is a release PR that upgrades versions and regenerates `cli` readme.
> Release of v0.9.1

- .github/workflows/deploy-release.yaml
This PR ...  
// Give a brief summary of changes introduced
> fix: action listening on wrong PR target branch
