src/hooks/setup-config.js
src/support/http/index.js
src/utils/general.js
test/utils/general.test.js

- Reorder to `pipe` to match `pipeAsync`

Reorder pipe

---

README.md
src/commands/api/get.js

Adds a note in `api:get --help` to show what version of SwaggerHub (since there are OnPrem versions) that `--resolved` is supported.

add help message for api:get

---

src/commands/api/get.js
src/commands/api/validate.js
src/commands/domain/get.js
src/requests/api.js
src/requests/domain.js
src/requests/spec.js
src/support/command/base-command.js
src/support/command/handle-response.js
src/template-strings/errors.js
test/commands/api/create.test.js
test/commands/domain/get.test.js

Currently we support retrieving APIs using the `api:get` command, this PR adds the ability to fetch domains using the new `domain:get` command.
Similar to the `api:get` command, the domain is returned in YAML format unless the --json flag is used.

feat: Add domain:get command

---

src/commands/api/get.js
src/commands/api/validate.js
src/commands/domain/publish.js
src/commands/domain/unpublish.js
src/commands/integration/create.js
src/requests/api.js
src/support/command/base-command.js
src/template-strings/errors.js
src/template-strings/info.js
src/utils/oas.js
test/commands/integration/create.test.js
test/resources/github.json

Adding feature to add API integrations. Will follow up with example configuration files and documentation.
Format of the command is: `swaggerhub integration:create org/api/version --file config.json`

feat: Add integration:create

---

examples/integrations/README.md
examples/integrations/github_basic.json
examples/integrations/gitlab_integration.json

The GitLab integration uses the `configType` of `GITLAB`
Similar config to the GitHub, but uses `personalAccessToken` instead of `token`

Adding GitLab Integration documentation

---

src/commands/integration/create.js

Updating the help description for the integration:create file flag which was incorrect.

Update help for file flag

---

README.md

This PR adds a new section to the README that explains how to use the `NODE_EXTRA_CA_CERTS` environment variable to specify custom trusted certificates for Node.js / SwaggerHub CLI. This is required to use CLI with SwaggerHub On-Premise instances that use self-signed or privately signed SSL certificates.
Fixes https://github.com/SmartBear/swaggerhub-cli/issues/125

docs: How to trust self-signed SSL certificates used by On-Premise instances

---

.gitignore
src/commands/api/get.js
src/commands/api/update.js
src/support/command/handle-response.js
src/template-strings/errors.js
test/commands/api/create.test.js
test/commands/api/get.test.js
test/commands/api/update.test.js
test/commands/domain/get.test.js

This change means that users will not unexpectedly see the privacy setting for a given API version set to private when they update an API using the CLI without specifying the --visibility flag.
@conor-ward @barryadk who else knows about this codebase and could help with review?

fix: Do not change visibility when flag is not provided

---

package.json

Updating license to the correct Apache 2.0 license identifier: https://spdx.org/licenses/

Update license to SPDX identifer 

---

examples/integrations/README.md

SwaggerHub On-Premise 1.26 is needed to use `integration:create`.
Fixes #145.

Add a note about On-Premise version that supports integration:create

---

src/commands/api/create.js
src/commands/api/publish.js
src/commands/api/setdefault.js
src/commands/api/update.js
src/commands/domain/publish.js
src/support/command/update-command.js
src/template-strings/info.js

The issue was caused by the Create / Update commands calling the Publish / SetDefault commands. The BaseCommand (when superclass of Publish/SetDefault) does not get the `this.id` value set, so we attempt to `split` on an undefined variable.
This fix refactors the functions to update the Publish and Default states into an `UpdateCommand`, which the existing Commands now extend (API Create, API Update, API Publish, API Set Default, Domain Publish).
This change removes duplicate code and avoids a Command object calling another Command.
I had some difficulty with naming `UpdateCommand`, since `CreateAPICommand` extends it. I'm open to suggestions but I think it accurately reflects the functions that the class provides.

Fixes #174 - API create/update fails when setting publish / default

---

README.md
src/commands/integration/create.js
src/commands/integration/update.js
src/support/command/parse-input.js
src/template-strings/info.js
test/commands/integration/create.test.js
test/commands/integration/update.test.js
test/support/parse-input.test.js

Add the ability to update the configuration of an integration.
Usage:
`swaggerhub integration:update Org/API/1.0.0/21e83842-bf83-43b0-abcd-21fde82d5 --file update.json`
* Moved the readConfigFile() function from the integration:create command into parse-input.js so that it can be reused by the integration:update command.

feat: Add integration update command

---

package.json

Currently `swaggerhub integration --help` reads the description of the first command and has that as the description for the topic
```
swaggerhub integration --help
creates a new API integration from a JSON configuration file.
```
This change adds its own separate description

docs: Update topic description for integration

---

src/commands/api/update.js
src/template-strings/info.js
test/commands/api/update.test.js

The API visibility endpoint was exposed on the public SwaggerHub API (accessible via API key) in the SwaggerHub on-premise 1.26. (`/apis/{owner}/{api}/{version}/settings/private`)
To support previous versions of SwaggerHub on-premise we can change the API check in `api:update` to fetch the API version rather than its visibility flag.
Previously the `isPrivate` query parameter was always sent when POSTing the update, using the current API's setting when the visibility flag is not passed. The query parameter is only required when changing the visibility so we do not need to fetch the current value.
This will only resolve the case where the API definition is being updated. If the `file` argument is not used then the visibility update endpoint is required and will fail on On-premise versions …

Remove visibility check before update

---

README.md

Changed `https://api.swaggerhub.com/` to `https://api.swaggerhub.com` because the URL with a trailing slash causes the commands to fail with an error
> Error: Please verify that the configured SwaggerHub URL is correct.

Remove trailing slash from the SWAGGERHUB_URL example value for SaaS

---

examples/integrations/README.md

The latest On-Premise version (1.27) now supports all `integrations` commands.
This PR updates the integrations README to mention this.

doc: Update the note about OnPrem versions in the integrations README

---

.github/workflows/build-master-push-to-aws.yaml
.github/workflows/build-master.yaml
.github/workflows/pull-request.yaml
README.md

* Node.js 10 went life of life on 2021-04-30 so we should remove offical support.
* Adding support for Node.js 16 as it is the current release.
* Moving the version in the build workflow to Node.js 12 as this is the current active LTS version.

!chore: Drop node.js 10 support. Add node.js 16 support

---

src/config/index.js
test/support/config.test.js

When developing with SwaggerHub, it's useful to run services locally (localhost). This change makes it possible to access these services using the CLI without returning an error.

feat: Allow SwaggerHub running on localhost

---

package-lock.json
package.json
src/utils/oas.js

* Updated js-yaml version 3.14.1 -> 4.1.0
The `safeLoad` function was renamed `load`.  Using `yaml.load()` in the code for clarity.

chore(deps): Update to js-yaml 4.1.0

---

README.md
src/commands/api/create.js
src/commands/api/publish.js
src/commands/api/unpublish.js
src/commands/api/update.js
src/commands/domain/create.js
src/commands/domain/publish.js
src/commands/domain/setdefault.js
src/commands/domain/unpublish.js
src/commands/domain/update.js
src/requests/domain.js
src/support/command/update-command.js
src/template-strings/info.js
test/commands/api/create.test.js
test/commands/api/update.test.js
test/commands/domain/create.test.js
test/commands/domain/setdefault.test.js
test/commands/domain/update.test.js

- Adds `domain:update` and `domain:setdefault` commands.
- Extract `updateVisibility` to `UpdateCommand` class.
- Add tests for update and setdefault.
- Change `publish` flag to `published=publish|unpublish` to allow unpublishing on update.

feat: Add domain update and setdefault commands

---

src/template-strings/errors.js
src/utils/oas.js
test/commands/api/create.test.js
test/commands/api/update.test.js
test/commands/domain/create.test.js
test/commands/domain/update.test.js

Improves error message when file incorrectly formatted.
Before -> 
```
swaggerhub-cli domain:update MixpanelDemo/DemoDomain -f ~/Downloads/MixpanelDemo-DemoDomain-1.0.0-domain.json
›   Error: There was a problem with parsing /Users/conor.ward/Downloads/MixpanelDemo-DemoDomain-1.0.0-domain.json. Ensure
›   the definition is valid. {"name":"YAMLException","reason":"missed comma between flow collection
›   entries","mark":{"name":null,"buffer":"{\n  \"info\" : {\n    \"description\" : \"This is a sample Domain updated by CLI
›    by version in file\",\n    \"version\" : \"1.0.0\",\n    \"title\" : \"Sample Domain\"\n  },\n  \"definitions\" : {\n
›     \"ErrorModel\" : {\n      \"required\" : [ \"code\", \"message\" ],\n      \"properties\" :\n        \"code\" : {\n
›          \"type\" : …
```

fix: Improve error message when parsing incorrectly formatted file

---

examples/integrations/README.md

Some updates to the integrations Readme:
* Add newly supported AWS regions `eu-south-1` and `af-south-1`.
* Add missing server codegens: OAS2 `java-pkmst`; OAS3 `jaxrs-cxf` and `jaxrs-spec` ([source](https://support.smartbear.com/swaggerhub/docs/whats-new.html#v2021-03-30)).

doc: Update the list of codegens and AWS regions

---

src/commands/project/spec/add.js
src/support/command/parse-input.js
src/template-strings/info.js
test/commands/project/spec/add.test.js

Added functionality to add a spec to an existing project
Part of #199 
- added command `swaggerhub project:spec:add organization/project_name apis my_api`
- added command `swaggerhub project:spec:add organization/project_name domains my_domain`

feat: Added functionality to add a spec to an existing project

---

src/commands/project/member/list.js
src/commands/project/spec/add.js
src/support/command/parse-input.js
src/template-strings/info.js
test/commands/project/member/list.test.js
test/commands/project/spec/add.test.js

Added functionality to list members of a project
Part of #199 
- Added command `swaggerhub project:member:list owner/project_name`
Currently this will return the names, types and roles associated with each user. Just wondering here if there may be an information disclosure worry for folks using this in CI in public projects? Should we have some granular way of choosing which data gets returned with flags?

feat: Added functionality to list members of a project

---

src/commands/project/member/list.js
src/commands/project/spec/add.js
src/commands/project/update.js
src/requests/project.js
src/support/command/parse-input.js
src/template-strings/info.js
test/commands/project/member/list.test.js
test/commands/project/spec/add.test.js
test/commands/project/update.test.js

Added functionality to update a project
Part of #199 
- added command `swaggerhub project update owner/project_name` with optional flags:
- `--description` (Description of project)
- `-a` or `--apis` (Comma separated list of api names to include in project)
- `-d` or `--domains` (Comma separated list of domain names to include in project)
- Added not in command description to inform user that using this command will overwrite whatever is currently saved, and that if they don't include all APIs/domains in the command with the appropriate flags they will be removed

feat: Added functionality to update a project

---

src/help.js

Changed variable imported in help.js to work with updated version of @oclif/plugin-help. This broke when @oclif/plugin-help was updated from 3.2.3 to 3.3.1 . Changed variable and --help flag now works again.
- Changed variable imported in help.js

fix: Changed variable imported in help.js to work with updated version of @oclif/plugin-help

---

package-lock.json
package.json
src/help.js

As per https://github.com/oclif/errors/pull/157 bumping @oclif/errors to 1.3.5 to get rid of false positive error message
- Update oclif errors to 1.3.5

chore: Update oclif errors to 1.3.5

---

.github/action/entrypoint.sh
Dockerfile

Updated Dockerfile to rectify IaC security warnings flagged by WhiteSource  
Closes #221 and #222 
- Added `appuser:appgroup` user to container to prevent running container as root   
- Added healthcheck command to try and reach ${SWAGGERHUB_URL} and fail if it cannot be reached  
- Modified entrypoint to use `gh_entrypoint.sh` instead of `/cli/bin/run`  
- Container can now be built with `docker build -t smartbear/swaggerhub-cli:latest .`
- and run with `docker run -e SWAGGERHUB_API_KEY="$API_KEY" -e SWAGGERHUB_URL="$SWH_URL" smartbear/swaggerhub-cli:latest $ARGS`
- Added linebreak in entrypoint.sh for showing output under prefix line

chore: Fix Dockerfile IaC WhiteSource violations

---

src/format-readme.js

Added script to format README after running oclif-dev readme
Proposed Changes
This script:
removes parameters in the header links
e.g. (#swaggerhub-apicreate-ownerapi_nameversion) => (#swaggerhub-apicreate)
removes arguments from headers
e.g. ## 'swaggerhub api:create OWNER/API_NAME/[VERSION]` => ## `swaggerhub api:create`
preserves all other artifacts in the README file, updating only the changed lines
Now, instead of just running oclif-dev readme, run `oclif-dev readme && node src/format-readme.js`

feat: Added script to format README after running `oclif-dev readme`

---

src/commands/project/member/list.js
src/support/command/parse-input.js
test/commands/project/create.test.js
test/support/parse-input.test.js

Small fix for project:create flags
- As caught by @MateuszPol in testing, added regex to remove whitespace in --api and --domain flags to ensure they get parsed correctly
- Update erroneous example string in project:member:list

fix: Added whitespace trimming for api and domain flags in project:create

---

.github/release.yaml

In light of the issues that came up when trying to automatically create the release for v0.6.0 (specifically with the [failed runs](https://github.com/SmartBear/swaggerhub-cli/runs/4854383216?check_suite_focus=true) of the `Release - SwaggerHub CLI on GitHub` action), I would like to propose an alternative flow for PRs and creating releases.  
Previously, we depended on a fork of the `generate-changelog` npm package that was in a [repo hosted by Rody Kirwan](https://github.com/Rody-Kirwan/generate-changelog) with a [GitHub Action workflow](https://github.com/SmartBear/swaggerhub-cli/blob/master/.github/workflows/release-on-github.yaml) that triggers whenever someone pushes a tag to the master branch prepended with `v*`. This external dependency failed yesterday when trying to create the …

Added release.yaml file for generating changelogs

---

src/commands/api/create.js
src/commands/api/update.js
src/commands/domain/create.js
src/commands/domain/update.js
src/template-strings/errors.js
src/utils/definitions.js
test/commands/api/create.test.js
test/resources/valid_asyncapi.json
test/resources/valid_asyncapi.yaml
test/support/parse-input.test.js

Closes #258  
This PR adds support for AsyncAPI definitions to the following commands:
- `api:create`
- `api:update`
- `domain:create`
- `domain:update`
- Add support for AsyncAPI to above commands.
- Rename `oas` fields to `specification` to bring in line with current SwaggerHub terminology.
- Rename `src/utils/oas` to `src/utils/definitions` to better convey what it is responsible for.

fix: Added AsyncAPI support to {api/domain}:{create/update} commands

---

src/commands/api/validate.js

This PR adds a fallback to the `api:validate` command to support legacy On-Premise installs of SwaggerHub

Add fallback to old validation endpoint for api:validate

---

src/utils/definitions.js
test/utils/definitions.test.js

This PR extends the `getSpecification` function to be able to differentiate between openapi-3.0.0 and openapi-3.1.0

Add support for openapi-3.1.0 specification param

---

src/commands/api/validate.js
test/commands/api/validate.test.js

This PR re-enables the exit codes for the `api:validate` command.

Fix exit codes for `api:validate` command

---

README.md
src/commands/api/validate.js
test/commands/api/validate.test.js

This PR adds the `-c/--fail-on-critical` flag to the `api:validate` command. 
When this flag is present, if there are critical standardization errors present in the referenced definition, the CLI with exit with error code `1`.
Also slight refactor of the existing tests for `api:validate` command.

Add `-c/--fail-on-critical` flag to `api:validate` command

---

package-lock.json
package.json
src/config/index.js
src/support/http/index.js
src/utils/general.js
test/commands/api/validate.test.js
test/support/config.test.js
test/support/inquirer.test.js
test/utils/general.test.js

This PR 
- Removes lodash as a dependency
- Updates existing methods and tests that used lodash
- Adds test case for api:validate command to bring coverage back up to 100%
All the lodash functions were implemented according to https://thescottyjam.github.io/snap.js/#!/nolodash

Remove lodash and update tests

---

.github/action/entrypoint.sh
Dockerfile

This PR updates the base node Docker image from using Node.js 12, which support was dropped as part of the swagger-cli 0.7.0 release. Now using the Node.js 18 as the base image.
Additionally replacing the usage of `set-output` which has been deprecated:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Resolves #290

Update Docker base image to node 18

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/action/README.md

Updating the documentation to use current versions. In particular the GitHub action example is often copy-pasted so it's good to suggest the latest version of actions/checkout. 
I've move the example of setting `SWAGGERHUB_URL` to the second example so that the first example is simpler.

Update versions in documentation

---

.github/action/entrypoint.sh

This PR uses the example from docs to fix GH Action as per https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-a-multiline-string

Use example from docs to fix GH Action

---

README.md
package-lock.json
src/commands/api/validate/index.js
src/commands/api/validate/local.js
src/requests/standardization.js
src/support/command/base-validate-command.js
test/commands/api/validate/index.test.js
test/commands/api/validate/local.test.js

This PR:
- Adds a new `api:validate:local` command that takes an API definition from the local filesystem and runs a standardization scan on it using the given organization's standardization configuration on SwaggerHub.
- Adds support for json output to the `api:validate/api:validate:local` commands as requested by https://github.com/SmartBear/swaggerhub-cli/issues/110#issuecomment-718302230
- Updates the output from the `api:validate/api:validate:local` commands to use `ux.table` to bring it in line with the tables in the rest of the codebase

Add api:validate:local command and refactor shared functions

---

src/commands/api/validate/index.js
test/commands/api/validate/index.test.js

This PR adds a check to the `api:validate` command to ensure the API exists and throw an error if it does not

Check if API exists in api:validate command

---

.github/dependabot.yaml

This PR adds groups for dependabot to group together the created PRs for:
- all `@oclif` dependencies
- all dev dependencies

Add dependency groups for dependabot

---

README.md
src/commands/api/validate/download-rules.js
src/requests/standardization.js
test/commands/api/validate/download-rules.test.js
test/resources/rulesets.js

This PR adds command that allows users to fetch their organization's standardization ruleset using Swaggerhub-CLI (Export functionality)

SWG-9025 Fetch organization standardization configuration command

---

.github/workflows/build-main.yaml
.github/workflows/pull-request.yaml

This pull request includes updates to the GitHub Actions workflows to support a newer version of Node.js and use the latest versions of certain actions.
Updates to GitHub Actions workflows:
* [`.github/workflows/build-main.yaml`](diffhunk://#diff-ed9008ce7f1c6c1ded18f4804e75aeb30f94697dc2eef5a1e5e2f5b1e73fd278L12-R16): Added Node.js version 22.x to the matrix and updated `actions/checkout` to v4 and `actions/setup-node` to v4.
* [`.github/workflows/pull-request.yaml`](diffhunk://#diff-a8619735ff14304aa0514284f86ff5145b0a6bae2e76a37faeb0ad899a3d8db4L10-R14): Added Node.js version 22.x to the matrix and updated `actions/checkout` to v4 and `actions/setup-node` to v4.

ci: added ci build and tests using node 22

---

package-lock.json
package.json

This pull request includes a minor update to the `package.json` file to ensure dependencies are up-to-date. 
Dependencies update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L13-R13): Updated the version of `@oclif/plugin-plugins` from `^5.0.9` to `^5.0.21`.
* run `npm update @oclif/plugin-plugins` to refresh lock file entries related to updated lib
This PR shall fix #498

fix: plugins-plugin bump 5.0.9 to 5.0.21

---

.github/workflows/deploy-release.yaml
.github/workflows/release-on-github.yaml

This pull request introduces a new workflow for deployment and modifies the existing release workflow to streamline the process of creating release branches and publishing releases. The most important changes include the addition of a deployment workflow, extraction of version information, tagging commits, and publishing to GitHub and npm.
* [`.github/workflows/deploy-release.yaml`](diffhunk://#diff-d8afbe8d1fc0b9fe347759a07853b35b70b0f3e4b1a22ded2ad0a5e1f6b28b76R1-R96): Added a new deployment workflow triggered by closed pull requests on the `test` branch. This workflow extracts the version from the source branch, tags the commit, and publishes the release to GitHub and npm.
* [`.github/workflows/release-on-github.yaml`](diffhunk://#diff-fc00ce6c11e271e0c8f700afbad93ef38e063a600c0449a8842 …

the release job updates versions, creates readme and release PR

---

.github/workflows/release-on-github.yaml

This PR fixes the release job mishandling of version passing between steps

fix: env was not passed to second step

---

.github/workflows/build-main.yaml
.github/workflows/codeql.yml
.github/workflows/deploy-release.yaml
.github/workflows/pull-request.yaml
.github/workflows/release-on-github.yaml

This PR freezes the version of OS that jobs are using so that change in -latest of Ubuntu does not influence the build and release process

ci: new ubuntu will soon be the -latest, freezing the version on 24.04

---

examples/integrations/README.md
examples/integrations/ibm_api_connect.json

IBM API Connect v5 has reached end of life and is no longer supported. 
- Remove IBM API Connect integration example configuration
- Remove IBM API Connect from README

Remove support for EoL IBM API Connect integration
